### ISSUE TITLE
Consider using standardlib email regex?

### ISSUE THREAD

**Issue by prognostikos** [substancelab/activemodel-email_address_validator#25]
This [change to the rails guides](https://github.com/rails/rails/pull/43832) was mentioned in the [Rails 7 release announcement](https://weblog.rubyonrails.org/2021/12/11/this-week-in-rails-rails-7-0-rc1-faster-template-rendering-better-tests-and-much-more-401a9df5/). It uses `URI::MailTo::EMAIL_REGEXP` to validate the email.

Not sure if it's relevant for this project or not, but it seemed worth mentioning :)

**Comment by koppen** [comment]
Thanks for the pointer, I didn't know Ruby had a builtin regex

That said, it is not relevant for us. The builtin regex matches the full syntax of allowed email addresses and we're specifically trying to not do that. 

In particular the email address mentioned in https://github.com/rails/rails/pull/43832, `email@123.123.12.123` is _not_ valid using activemodel-email_address_validator; no user has ever wanted to sign up with that. Neither do we accept `email@localhost` or other email addresses highly unlikely to actually used in a real-world-facing application.

If one needed to accept those address, one could probably just do

    validates :email, :format => {:with => URI::MailTo::EMAIL_REGEXP}
